**2) 작업형 제1유형**

01.	주어진 trash bag 데이터 세트는 지역별 종량제 봉투 가격을 나타낸다. 가격 컬럼은 각 행의 조건을 만족하는 해당 용량의 종량제 봉투가 존재하면 가격을 값으로, 존재하지 않으면 0을 값으로 갖는다. 이때 용도가 ‘음식물쓰레기’이고 사용 대상이 ‘가정용’인 2L 봉투 가격의 평균을 소수점을 버린 후 정수로 출력하시오.

In [1]:
# 라이브러리 및 데이터 불러오기
import pandas as pd
df1 = pd.read_csv('./data/5_1_trash_bag.csv',encoding = 'cp949')
df1.head()

,시도명,시군구명,종류,처리방식,용도,사용대상,1L가격,1.5L가격,2L가격,2.5L가격,...,5L가격,10L가격,20L가격,30L가격,50L가격,60L가격,75L가격,100L가격,120L가격,125L가격
0,강원도,강릉시,규격봉투,매립용,생활쓰레기,기타,0,0,0,0,...,130,270,520,0,1250,0,1880,0,0,0
1,강원도,강릉시,재사용규격봉투,매립용,생활쓰레기,기타,0,0,0,0,...,0,270,520,0,0,0,0,0,0,0
2,강원도,고성군,규격봉투,소각용,생활쓰레기,가정용,0,0,0,0,...,140,260,500,0,1220,0,0,2410,0,0
3,강원도,고성군,규격봉투,소각용,음식물쓰레기,가정용,0,0,60,0,...,120,0,0,0,0,0,0,0,0,0
4,강원도,고성군,특수규격마대,매립용,생활쓰레기,가정용,0,0,0,0,...,0,0,0,0,1540,0,0,0,0,0

In [2]:
# 조건에 맞는 데이터 추출
filtered_data = df1[(df1['용도']=='음식물쓰레기')&(df1['사용대상']=='가정용')]
filtered_data.head()

,시도명,시군구명,종류,처리방식,용도,사용대상,1L가격,1.5L가격,2L가격,2.5L가격,...,5L가격,10L가격,20L가격,30L가격,50L가격,60L가격,75L가격,100L가격,120L가격,125L가격
3,강원도,고성군,규격봉투,소각용,음식물쓰레기,가정용,0,0,60,0,...,120,0,0,0,0,0,0,0,0,0
8,강원도,삼척시,규격봉투,매립용,음식물쓰레기,가정용,0,0,0,0,...,80,150,290,0,0,0,0,0,0,0
9,강원도,양구군,규격봉투,매립용,음식물쓰레기,가정용,0,0,50,0,...,120,210,400,0,0,0,0,0,0,0
12,강원도,양양군,규격봉투,기타,음식물쓰레기,가정용,0,0,40,0,...,90,170,340,0,0,0,0,0,0,0
16,강원도,영월군,규격봉투,매립용,음식물쓰레기,가정용,0,0,0,0,...,110,180,350,0,900,0,1350,0,0,0

In [3]:
# 2L가격 열에서 가격이 0이 아닌 데이터의 평균 계산 및 정수 출력
average_price = filtered_data[filtered_data['2L가격'] != 0]['2L가격'].mean()
result = int(average_price)
print(result)

119

**2) 작업형 제1유형**

02.	BMI 지수는 몸무게(kg)를 키(m)의 제곱으로 나누어 구하며, BMI값에 따른 비만도 분류는 다음과 같다. 이 때 주어진 bmi 데이터 세트에서 비만도가 정상에 속하는 인원 수와 과체중에 속하는 인원 수의 차이를 정수로 출력하시오.

In [4]:
# 라이브러리 및 데이터 불러오기
df2 = pd.read_csv('./data/5_2_bmi.csv')
df2.head()

   Gender  Height  Weight
0    Male     174      96
1    Male     189      87
2  Female     185     110
3  Female     195     104
4    Male     149      61

In [5]:
# BMI 지수 계산
df2['BMI'] = df2['Weight']/((df2['Height']/100)**2)
df2.head()

   Gender  Height  Weight        BMI
0    Male     174      96  31.708284
1    Male     189      87  24.355421
2  Female     185     110  32.140248
3  Female     195     104  27.350427
4    Male     149      61  27.476240

In [6]:
# '정상' 범주와 '과체중' 범주에 해당하는 인원 수 계산
# '정상' 범주 인원 수
normal = df2[(df2['BMI'] >= 18.5)&(df2['BMI'] < 23)].shape[0]
# '과체중' 범주 인원 수
overweight = df2[(df2['BMI'] >= 23)&(df2['BMI']<25)].shape[0]

In [7]:
# '정상'과 '과체중' 사이의 차이 계산 및 결과 출력
result = normal - overweight
print(result)

28

**2) 작업형 제1유형**

03.	주어진 students 데이터 세트는 각 학교의 학년별 총 전입학생, 총 전출학생, 전체 학생 수를 나타낸다. 순 전입학생 수는 총 전입학생 수에서 총 전출학생 수를 빼서 구할 수 있다. 순 전입학생이 가장 많은 학교의 전체 학생 수를 구하시오.

In [8]:
# 라이브러리 및 데이터 불러오기
df3 = pd.read_csv('./data/5_3_students.csv', encoding = 'cp949')
df3.head()

  학교  학년  총 전입학생  총 전출학생  전체 학생 수
0  A   1       9       1      222
1  A   2      13       4      148
2  A   3       8       7      196
3  B   1       7       5      171
4  B   2       9       1      216

In [9]:
# 순 전입학생 수 계산
df3['순 전입학생'] = df3['총 전입학생'] - df3['총 전출학생']
df3.head()

  학교  학년  총 전입학생  총 전출학생  전체 학생 수  순 전입학생
0  A   1       9       1      222       8
1  A   2      13       4      148       9
2  A   3       8       7      196       1
3  B   1       7       5      171       2
4  B   2       9       1      216       8

In [10]:
# 학교별 순 전입학생의 합계와 전체 학생 수의 합계 계산
school_summary = df3.groupby('학교').agg({'순 전입학생':'sum','전체 학생 수':'sum'}).reset_index()
school_summary

  학교  순 전입학생  전체 학생 수
0  A      18      566
1  B      13      588
2  C      -9      528
3  D       7      548
4  E      14      603
5  F       1      481
6  G      10      618
7  H      -1      602

In [11]:
# 순 전입학생이 가장 많은 학교의 전체 학생 수 출력
result = school_summary.loc[school_summary['순 전입학생'].idxmax(),'전체 학생 수']
print(result)

566

**3) 작업형 제2유형**


01. 다음은 Used car 데이터 세트이다. 주어진 훈련 데이터 세트를 활용하여 중고차의 판매 가격을 예측하고 해당 예측 결과를 csv 파일로 제출하시오.
* 결과 제출 양식 : 제출한 양식의 rmse 평가 지표 값을 통해 영역별 배점에 따라 최종 점수가 반영될 예정

In [12]:
# 라이브러리 불러오기
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import OneHotEncoder

In [13]:
# 데이터 불러오기
X_train = pd.read_csv('./data/5_4_x_train.csv')
y_train = pd.read_csv('./data/5_4_y_train.csv')['price']
X_test = pd.read_csv('./data/5_4_x_test.csv')

In [14]:
X_train.head()
X_train['transmission'].unique()

array(['Automatic', 'Semi-Auto', 'Manual'], dtype=object)

In [16]:
y_train.head()

0    21350
1    69691
2    42950
3    31470
4    27495
Name: price, dtype: int64

In [17]:
# 'id' 열 제거
X_train.drop(columns = ['id'], inplace = True)
X_test.drop(columns = ['id'], inplace = True)

In [18]:
# 데이터 형태 확인
print(X_train.shape,y_train.shape,X_test.shape)

(7468, 8) (7468,) (3200, 8)

In [19]:
y_train.head()

0    21350
1    69691
2    42950
3    31470
4    27495
Name: price, dtype: int64

In [20]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7468 entries, 0 to 7467
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         7468 non-null   object
 1   year          7468 non-null   int64
 2   transmission  7468 non-null   object
 3   mileage       7468 non-null   int64
 4   fuelType      7468 non-null   object
 5   tax           7468 non-null   int64
 6   mpg           7468 non-null   float64
 7   engineSize    7468 non-null   float64
dtypes: float64(2), int64(3), object(3)
memory usage: 466.9+ KB

In [21]:
# 결측치 기본 정보 확인
X_train.isnull().sum()

model           0
year            0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [22]:
X_test.isnull().sum()

model           0
year            0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [23]:
# 데이터 세부 정보 확인
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7468 entries, 0 to 7467
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         7468 non-null   object
 1   year          7468 non-null   int64
 2   transmission  7468 non-null   object
 3   mileage       7468 non-null   int64
 4   fuelType      7468 non-null   object
 5   tax           7468 non-null   int64
 6   mpg           7468 non-null   float64
 7   engineSize    7468 non-null   float64
dtypes: float64(2), int64(3), object(3)
memory usage: 466.9+ KB

In [24]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3200 entries, 0 to 3199
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         3200 non-null   object
 1   year          3200 non-null   int64
 2   transmission  3200 non-null   object
 3   mileage       3200 non-null   int64
 4   fuelType      3200 non-null   object
 5   tax           3200 non-null   int64
 6   mpg           3200 non-null   float64
 7   engineSize    3200 non-null   float64
dtypes: float64(2), int64(3), object(3)
memory usage: 200.1+ KB

In [25]:
X_train['model'].unique()

array([' A1', ' RS4', ' A8', ' Q5', ' A5', ' Q3', ' R8', ' Q2', ' A3',
       ' A6', ' A4', ' TT', ' Q7', ' RS6', ' A7', ' S4', ' Q8', ' RS3',
       ' SQ5', ' RS5', ' S3', ' SQ7', ' A2', ' RS7', ' S8', ' S5'],
      dtype=object)

In [26]:
X_test['model'].unique()

array([' A4', ' A6', ' Q5', ' A1', ' A3', ' Q2', ' Q7', ' Q8', ' Q3',
       ' A5', ' TT', ' R8', ' RS6', ' A7', ' A8', ' SQ5', ' S3', ' S4',
       ' RS4', ' RS5', ' SQ7', ' RS3'], dtype=object)

In [27]:
# 원 핫 인코딩
# get_dummies 함수 사용
# drop_first=True 옵션은 각 범주형 변수에서 첫 번째 범주를 제외시켜 더미 변수의 함정(dummy variable trap)을 피할 수 있게 해준다.

X_train_preprocessed = pd.get_dummies(X_train, drop_first= True)
X_test_preprocessed= pd.get_dummies(X_test, drop_first=True)

In [28]:
X_train_preprocessed.head()

,year,mileage,tax,mpg,engineSize,model_ A2,model_ A3,model_ A4,model_ A5,model_ A6,...,model_ S4,model_ S5,model_ S8,model_ SQ5,model_ SQ7,model_ TT,transmission_Manual,transmission_Semi-Auto,fuelType_Hybrid,fuelType_Petrol
0,2019,3500,145,40.9,2.0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,2020,2500,145,28.8,2.9,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
2,2019,500,145,40.4,3.0,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,2019,5089,150,38.2,2.0,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
4,2020,4951,145,51.4,2.0,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False

In [29]:
X_test_preprocessed.head()

,year,mileage,tax,mpg,engineSize,model_ A3,model_ A4,model_ A5,model_ A6,model_ A7,...,model_ RS6,model_ S3,model_ S4,model_ SQ5,model_ SQ7,model_ TT,transmission_Manual,transmission_Semi-Auto,fuelType_Hybrid,fuelType_Petrol
0,2020,4000,145,54.3,3.0,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,2016,31300,30,61.4,2.0,False,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
2,2019,11296,150,38.2,2.0,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,2018,6500,145,55.4,1.4,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
4,2016,31524,30,60.1,1.4,True,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True

In [30]:
# 훈련 세트에 있는 컬럼과 테스트 세트에 있는 컬럼을 맞추기
X_test_preprocessed = X_test_preprocessed.reindex(columns = X_train_preprocessed, fill_value=0)

In [31]:
# 모델 훈련
linear_model = LinearRegression()
random_forest_model = RandomForestRegressor()
nn_model = MLPRegressor(max_iter=500)

linear_model.fit(X_train_preprocessed,y_train)
random_forest_model.fit(X_train_preprocessed, y_train)
nn_model.fit(X_train_preprocessed, y_train)

c:\Users\hyunk\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

MLPRegressor(max_iter=500)

In [32]:
# 모델 평가
y_pred_linear = linear_model.predict(X_train_preprocessed)
y_pred_rf = random_forest_model.predict(X_train_preprocessed)
y_pred_nn = nn_model.predict(X_train_preprocessed)

rmse_linear = np.sqrt(mean_squared_error(y_train,y_pred_linear))
rmse_rf = np.sqrt(mean_squared_error(y_train,y_pred_rf))
rmse_nn = np.sqrt(mean_squared_error(y_train,y_pred_nn))

print(rmse_linear,rmse_rf,rmse_nn)

3726.013505237629 944.255820973966 5583.776249226082

In [33]:
# 예측 결과를 데이터프레임 형식으로 변환
results = pd.DataFrame({'id':range(1,len(y_pred_rf)+1),'price':y_pred_rf})
print(results)

        id         price
0        1  21874.920000
1        2  69510.930000
2        3  43353.350000
3        4  32586.610000
4        5  28007.620000
...    ...           ...
7463  7464  16740.860000
7464  7465  17567.970000
7465  7466  21456.900000
7466  7467  29098.106429
7467  7468  16322.580000

[7468 rows x 2 columns]

In [34]:
# 수험번호.csv 파일로 저장
results.to_csv('./output/00000,csv',index=False)